### ISSUE TITLE
Add config option to specify lodash targets to run

### ISSUE THREAD

**Issue by tauren** [jjt/grunt-lodash-autobuild#2]
Another suggestion is to add a configuration option to run a specific lodash target instead of all of them. The last line of grunt-lodash-autobuild executes all lodash targets:

``` javascript
grunt.task.run('lodash')
```

My lodash config looks like this:

``` javascript
    lodash: {
      build: {
        dest: 'app/vendor/lodash.build.js',
        options: {
          exports: ['amd'],
          flags: [
            '--debug'
          ]
        }
      },
      test: {
        dest: 'tests/vendor/lodash.full.js',
        options: {
          exports: ['amd'],
          flags: [
            '--debug'
          ]
        }
      }
    },
    lodashAutobuild: {
      src: ['app/js/**/*.js'],
      options: {
        lodashConfigPath: 'lodash.build.options.include',
        lodashObjects: [ '_' ]
      }
    },
```

In my app, Grunt is configured to rebuild `lodash.build.js` during a watch task, whenever any `app/**/*.js` files are changed. 

I'd prefer to not waste time rebuilding the full version of lodash for my tests. I want a different watch task to do that when any test files change.

**Comment by jjt** [comment]
Yeah, that would be a good feature to implement. I'm not sure when I'll have a chance to work on it, but I'll accept pull requests if you want to take a crack at it.
